DWAPlannerROS:
  # Hunter 차량 운동학적 제약 (더 보수적으로 설정)
  max_vel_x: 1.0          # 최대 1.5m/s이지만 안전을 위해 1.0m/s로 제한
  min_vel_x: -0.2         # 후진 속도 감소
  max_vel_y: 0.0          # 차량이므로 측면 이동 불가
  min_vel_y: 0.0
  max_vel_trans: 1.0
  min_vel_trans: 0.05
  
  # 각속도 제한 (후륜구동 차량 특성 반영)
  # max_angular_vel = max_linear_vel / min_turning_radius
  # Hunter: min_radius ≈ 0.65/tan(0.461) ≈ 1.3m
  # 따라서 max_angular ≈ 1.0/1.3 ≈ 0.77 rad/s
  max_vel_theta: 0.75     # 물리적 한계 기반 각속도 제한
  min_vel_theta: -0.75
  
  # 가속도 제한 (차량의 부드러운 움직임을 위해)
  acc_lim_x: 0.3          # 선가속도 더 부드럽게
  acc_lim_y: 0.0
  acc_lim_theta: 0.5      # 각가속도 더 부드럽게
  acc_lim_trans: 0.3
  
  # 목표 허용 오차
  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.3
  latch_xy_goal_tolerance: true
  
  # 경로 추적 가중치 (차량 특성에 맞게 조정)
  path_distance_bias: 60.0    # 경로 추종을 더욱 중요하게
  goal_distance_bias: 15.0    # 목표 지향성 약간 감소
  occdist_scale: 0.01         # 장애물 회피 민감도 감소
  
  # Hunter 차량 기하학적 특성 반영
  forward_point_distance: 0.4  # wheelbase 고려한 전방 예측 거리
  stop_time_buffer: 0.5        # 정지 버퍼 시간 증가
  scaling_speed: 0.2
  max_scaling_factor: 0.15
  
  # 발진 방지 강화
  oscillation_reset_dist: 0.2
  
  # DWA 특정 파라미터 (차량용 최적화)
  sim_time: 3.0               # 더 긴 예측 시간으로 안정성 향상
  sim_granularity: 0.025      # 더 세밀한 시뮬레이션
  vx_samples: 10              # 선속도 샘플 증가
  vy_samples: 1               # 차량이므로 1개만
  vtheta_samples: 20          # 각속도 샘플링
  
  # 차량 특성 반영
  penalize_negative_x: true   # 후진 페널티
  
  # 차량 전용 추가 파라미터
  holonomic_robot: false      # 비홀로노믹 로봇 (차량)
  escape_reset_dist: 0.1      # 벗어나기 거리
  escape_reset_theta: 0.1     # 벗어나기 각도
  
  # 추가 안전 파라미터
  prefer_forward: true        # 전진 선호
  simple_attractor: false     # 복잡한 경로 계획 사용
  
  # 발행 설정
  publish_traj_pc: true
  publish_cost_grid_pc: false  # 성능 향상을 위해 비활성화
  global_frame_id: odom