global_costmap:
  global_frame: map
  robot_base_frame: imu_link  # base_link 대신 imu_link 사용
  update_frequency: 2.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 50.0
  height: 50.0
  resolution: 0.2
  transform_tolerance: 1.0
  
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}