# Move Base 파라미터
shutdown_costmaps: false
controller_frequency: 10.0
controller_patience: 15.0
planner_frequency: 1.0
planner_patience: 5.0
oscillation_timeout: 0.0
oscillation_distance: 0.5
base_global_planner: "global_planner/GlobalPlanner"
base_local_planner: "dwa_local_planner/DWAPlannerROS"

# 복구 동작
recovery_behavior_enabled: true
clearing_rotation_allowed: true
aggressive_reset: false

# Global Planner 파라미터
GlobalPlanner:
  allow_unknown: true
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false
  lethal_cost: 253
  neutral_cost: 50
  cost_factor: 3.0
  publish_potential: false